# Generated by Django 4.1.7 on 2023-04-03 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
