# Generated by Django 4.1.7 on 2023-04-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, default="Address isn't given."),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
