# Generated by Django 4.1.7 on 2023-04-04 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_userprofile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
